### PR TITLE
Add support for MySQL initialization script

### PR DESCRIPTION
**Pull request by EPMatt**
Hi there,

First of all thank you so much for developing such a useful set of docker images. This project makes setting up the LAMP stack a breeze! 🎉 

While using your images, I needed not only to provide a custom app to the web server, but also to initialize a database with custom data, prior to the container's first boot. This includes multiple databases, tables, users etc. 

With this PR I'm adding support for a MySQL initialization script, which can be optionally provided by the user as a volume mount to `/db/init.sql`. In my opinion such solution provides the most flexible way to allow users to initialize the MySQL instance, custom-tailored to their specific needs.

The SQL script will be executed only on the container first run, or more generally, if `/var/lib/mysql` doesn't contain initialized data.

I successfully tested my changes on `docker-lamp_web2004-php8:latest`; however, I wasn't able to run the one-line testing command without errors. I also noticed that the testing command fails even when run directly on the `master` branch.

I edited relevant sections in the docs as well, adding a description of this new feature.

Hope you'll find my contribution valuable for the project. I'd be happy to help if you need additional information or you'd like to suggest further changes. :) 

Thank you for your precious time and for maintaining such a cool project!

### CODE REVIEW

**Comment by gmarmstrong** [comment]
Suggested a small edit: https://github.com/EPMatt/docker-lamp/pull/1

**Comment by vendethiel** [comment]
Also interested in this!

**Comment by Ymil** [comment]
That's good, I'm waiting for it to be published.

**Comment by mattrayner** [comment]
This has now been release ad part of the latest 20.04 tags

**Pull request merged**
