### PR TITLE
Install cURL

### PR DESCRIPTION
**Pull request by meowsus**
Hey @mattrayner 

First of all this container, my friend, is excellent. It has saved my ass 10 times over. I thank you!

I was just doing a WooCommerce build that required a Stripe extension integration and got the message that the cURL package was not installed. Since many libraries require cURL as a dependency, I figured it wouldn't hurt to shoot this PR your way.

Let me know what you think.

Thank you, thank you, thank you again.

### CODE REVIEW

**Comment by mattrayner** [comment]
Hi @meowsus,
 Thanks for your kind words and contribution :) I'm more than happy to merge it in, if you could also update Dockerfile1404 to keep compatibility?

Thanks again for your great contribution :)

**Comment by meowsus** [comment]
Hey @mattrayner 

Sorry for the delay on this. I spaced out hard.

Thanks again!

**Comment by meowsus** [comment]
Hey Matt,

Does this look good to you? Anything else you need me to do?

**Comment by mattrayner** [comment]
Thanks for your contribution :)

**Pull request merged**
