### PR TITLE
Errors in file that stopped mySQL from starting up.

### PR DESCRIPTION
**Pull request by rmdave**
MySQL wouldn't startup

### CODE REVIEW

**Comment by mattrayner** [comment]
Sorry, didn't notice this until I did my commit, why did you need to change line 84?

> mysqld --initialize-insecure > /dev/null 2>&1

**Comment by pzhlkj6612** [comment]
I guess that he want to get the details about mysqld errors during its startup.

**Comment by mattrayner** [comment]
That seems fair 😂

**Comment by mattrayner** [comment]
Merging this in now so that I can package this into a release

**Pull request merged**
