### PR TITLE
Bugfixed image not running with php>7.2

### PR DESCRIPTION
**Pull request by mahmoudajawad**
As discussed in #74

### CODE REVIEW

**Comment by mattrayner** [comment]
I'll run the tests then I'm happy to merge this, thanks for the contribution!

**Comment by mattrayner** [comment]
I'm having issues running the tests locally, but I am working on this

**Comment by mattrayner** [comment]
One additional comment is that this only patches image 1804, I'm guessing this also needs to be ported onto the 1604 image?

**Comment by mattrayner** [comment]
Included in #79

**Comment by mattrayner** [comment]
@mahmoudajawad thanks again for your contribution, this is great :)

**Comment by mahmoudajawad** [comment]
hello @mattrayner.
Sorry for not being able to reply before your merged the PR. I believe you already found the answers, and I'm glad I was able to help you with this amazing project.

**Pull request closed without merging**
